config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Home
  get 'home/index'
  get 'home/login'
  get 'home/signup'

  # User
  resources :users

  # Confirmations
  resources :confirmations, only: %i[new create show], param: :token

  # Defines the root path route ("/")
  root to: redirect('/home/index')
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end

  def login; end

  def signup
    redirect_to new_user_url
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div style="text-align: center; padding: 50px; font-family: Arial, sans-serif;">
  <h1 style="color: #333;">Welcome to Medical Appointment Scheduler!</h1>
  <p style="font-size: 20px; color: #666;">We are glad to have you here!</p>

  <div style="margin-top: 50px;">
    <%= link_to "Login", home_login_path, style: "background-color: #007BFF; color: #fff; padding: 15px 30px; text-decoration: none; border-radius: 5px; margin-right: 20px;" %>
    <%= link_to "Signup", home_signup_path, style: "background-color: #28A745; color: #fff; padding: 15px 30px; text-decoration: none; border-radius: 5px;" %>
  </div>
</div>

app/views/home/login.html.erb
<h1>Home#login</h1>
<p>Find me in app/views/home/login.html.erb</p>

app/views/home/signup.html.erb
<h1>Home#signup</h1>
<p>Find me in app/views/home/signup.html.erb</p>